from __future__ import annotations

from .schemas import ReviewFinding, ReviewReport, Severity


def render_markdown_report(report: ReviewReport, max_findings: int = 12) -> str:
    lines = [
        "## AI PR Review",
        "",
        f"**Summary:** {report.summary.headline}",
        "",
        "| Metric | Value |",
        "| --- | --- |",
        f"| Files changed | {report.summary.changed_files} |",
        f"| Additions / deletions | +{report.summary.additions} / -{report.summary.deletions} |",
        f"| Risk level | {report.summary.risk_level.value} |",
        f"| Model | {report.model_used or 'local deterministic analyzer'} |",
        "",
        "### Change Summary",
    ]
    lines.extend(f"- {bullet}" for bullet in report.summary.bullets)
    lines.extend(["", "### Review Suggestions"])

    if not report.findings:
        lines.append("- No actionable findings detected. Please still perform normal human review.")
    else:
        for finding in report.findings[:max_findings]:
            lines.extend(_render_finding(finding))

    lines.extend(
        [
            "",
            "_Generated by AI PR Review Tool. Findings include confidence scores "
            "and should be verified by a human reviewer._",
        ]
    )
    return "\n".join(lines)


def _render_finding(finding: ReviewFinding) -> list[str]:
    location = ""
    if finding.file_path:
        location = f" `{finding.file_path}`"
        if finding.line:
            location += f":{finding.line}"

    icon = {
        Severity.critical: "[critical]",
        Severity.high: "[high]",
        Severity.medium: "[medium]",
        Severity.low: "[low]",
        Severity.info: "[info]",
    }[finding.severity]

    lines = [
        "",
        f"- **{icon} {finding.title}**{location}",
        f"  - Category: `{finding.category.value}`; "
        f"confidence: `{finding.confidence:.2f}`; source: `{finding.source}`.",
        f"  - Why it matters: {finding.body}",
        f"  - Recommendation: {finding.recommendation}",
    ]
    if finding.evidence:
        evidence = finding.evidence.replace("\n", " ")[:240]
        lines.append(f"  - Evidence: `{evidence}`")
    return lines
